#!/usr/bin/python3

def factorize(n):
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factor1 = i
            factor2 = n // i
            print(f"{n}={factor2}*{factor1}")
            return

    # If no factors found, the number is prime
    print(f"{n} is a prime number")

def main():
    import sys

    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    file_path = sys.argv[1]

    try:
        with open(file_path, 'r') as file:
            for line in file:
                number = int(line.strip())
                factorize(number)

    except FileNotFoundError:
        print("Error: File not found.")
        sys.exit(1)

if __name__ == "__main__":
    main()
